# spring.application.name=book-api
server:
  port: 7070

spring: 
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2dll:
          create_namespaces: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://${DB_HOST:book-api-mysql}:${DB_PORT:3306}/${DB_NAME:dev}?createDatabaseIfNotExist=true
    username: ${DB_USER:mysql}
    password: ${DB_PASSWORD:thisIsReallyStrongPassword123}
    driver-class-name: com.mysql.cj.jdbc.Driver